### ISSUE TITLE
简单测了下，用的最新的Android studio 没有跑起来

### ISSUE THREAD

**Issue by shesio** [FlyJingFish/ModuleCommunication#2]
点击go login 里面的两个功能按钮，第一个没有反应，第二个闪退

**Comment by FlyJingFish** [comment]
你直接clone的我的项目吗，如果是的话，我的demo 写的有点问题，没有及时改回来。但应该是第一个跳转了，第二个没反应。你那边这个反应是不正常

**Comment by FlyJingFish** [comment]
你用的Android studio 的版本是多少？mac电脑吗

**Comment by shesio** [comment]
window11：Android Studio Koala | 2024.1.1
Build #AI-241.15989.150.2411.11948838, built on June 11, 2024
Runtime version: 17.0.10+0--11609105 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 11.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
  com.intellij.marketplace (241.15989.206)
  Dart (241.17502)
  GsonFormatPlus (1.6.1)
  org.jetbrains.compose.desktop.ide (1.6.2)
  com.github.copilot (1.5.17.6356)
  io.flutter (80.0.2)
  cn.yiiguxing.plugin.translate (3.6.2)

**Comment by FlyJingFish** [comment]
我这边用最新版AS测试无问题，然后我更新了下demo，你可再次更新下代码尝试一下
